# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

defaults: &defaults
  docker:
      - image: cimg/node:13.8.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - save_cache:
          paths:
            - "./node_modules"
          key: "node_modules"
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: 
          key: "node_modules"
      - run: npm i
      - run: npm run test
  analyze:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: 
          key: "node_modules"
      - run: npm i
      - run: npm audit
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  ci-workflow:
    jobs:
      - build
      - test:
          requires:
            - "build"
      - analyze:
          requires:
            - "test"
